### ISSUE TITLE
'Profile Info' button was crashing .. 

### ISSUE THREAD

**Issue by coreymalek** [mypalal84/twitter-client#8]
![screen shot 2017-03-23 at 10 30 32 am](https://cloud.githubusercontent.com/assets/18276076/24261343/e5de8212-0fb3-11e7-8d96-19ccfc55967f.png)

I was able to fix it. The crash was because there was a disconnect between your 'ProfileViewController' and the module (your actual project). All I did was retype 'ProfileViewController' and hit 'enter' and it fixed it. This little piece of functionality is very finnicky and can cause frequent crashes. So just fix that piece and it should work just fine! Any questions just let me know :)

**Comment by mypalal84** [comment]
Thanks, I fixed that issue. Now on to all the other ones...
